### ISSUE TITLE
Menu.

### ISSUE THREAD

**Issue by LuizCBonini** [wesleyara/churrascometro#1]
Oi Wesley tudo bom?
 Primeiramente, parabéns pelo projeto criado, gostei muito e me diverti testando ele com minha esposa, talvez eu até passe a usa-lo com frequência.
  Entretanto, percebi que os botões no menu não foram linkados no programa, eu gostaria muito de ver as motivações e a métrica que você usou.

**Comment by wesleyara** [comment]
Opa Luiz, tudo bem e com você?
Eu estou só começando esse repositório, pode ter certeza que irei colocar tudo direitinho e implementar mais coisas para interagir com a página, não se preocupe que vai ter tudo bem descrito.
Caso queira que eu acrescente alguma coisa, é só falar que eu vou olhar com bastante atenção. Abraços!

**Comment by wesleyara** [comment]
Olá Luiz, já foi implementado o que você estava a procura. Mais adiante o projeto irá sendo atualizado.

**Comment by wesleyara** [comment]
Olá Luiz, já foi implementado o que você estava a procura. Mais adiante o projeto irá sendo atualizado.
